# Site settings
title:       "InfinniUI"
email:       "info@infinnity.ru"
phone:       "+7 (351) 236-20-60"
address:     "454000, Челябинск, ул.Северная, 52/2"
copyright:   "Infinnity Solutions Ltd"

url:       "http://localhost:4000"
baseUrl:   ""

# Services
disqus:          "docs-infinnity-ru"
yandexMetrika:   "30185399"
googleAnalytics: "UA-62864649-1"

# Handling Reading
safe:         false
keep_files:   [".git",".hg"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
exclude:      ["*.confluence", ".git", ".idea", "docs/_obsolete"]

# Serving
detach: false
port:   4000
host:   127.0.0.1

# Outputting
permalink: pretty

# kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# GitHub
github:
 owner: "InfinniPlatform"
 repo:  "InfinniUI-schema"
 name:  "InfinniUI"

gems: [jekyll-paginate, jekyll-gist]
