# Site settings
title:       "InfinniPlatform"
email:       "info@infinnity.ru"
phone:       "+7 (351) 236-20-60"
address:     "454000, Челябинск, ул.Северная, 52/2"
copyright:   "Infinnity Solutions Ltd"

url:     "http://localhost:4000"
baseurl: ""

# Handling Reading
safe:         false
keep_files:   [".git",".hg"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
exclude:      ["*.confluence"]

# Conversion
markdown:    redcarpet
highlighter: pygments

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink: pretty

# RedCarpet
redcarpet:
 extensions: ["no_intra_emphasis","tables","autolink","fenced_code_blocks","space_after_headers","with_toc_data"]

 # Pagination
paginate: 10
paginate_path: "/blog/page:num/"
